---
title: Disable Click To Do
description: Disables the Click To Do AI feature
builds: [ '>=22000' ]
actions:
  - !cmd:
    command: '"AtlasDesktop\3. General Configuration\AI Features\Click To Do\Disable Click To Do (default).cmd" /silent'
    exeDir: true
    wait: true
    runas: currentUserElevated

